name: 'Install picotool'
description: 'Installs the picotool executable from raspberry/picotool.'
runs:
  using: "composite"
  steps:

    - name: Cache picotool
      id: cache-picotool
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/picotool
        key: ${{ runner.os }} # we (currently) hardcode the version so no need to get fancy

    # Check out the SDK (used by picotool)
    - name: Checkout pico-sdk
      if: steps.cache-picotool.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        ref: a1438dff1d38bd9c65dbd693f0e5db4b9ae91779

    # Check out picotool itself
    - name: Checkout picotool
      if: steps.cache-picotool.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/picotool
        path: picotool
        ref: 25aa087b2c517b4901874a99536e869d4d27b678

    # Build and install
    - name: Build picotool
      if: steps.cache-picotool.outputs.cache-hit != 'true'
      run: |
        export PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk
        cd $GITHUB_WORKSPACE/picotool
        mkdir build
        cd build
        # build picotool without usb support: we don't
        # need usb support and it would add a system
        # dependency.
        PICOTOOL_NO_LIBUSB=1 cmake ..
        make
        sudo make install
      shell: bash

    - name: Run picotool
      run: picotool version
      shell: bash
