# Build the project and upload binaries as artifacts
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
        with:
          target: thumbv6m-none-eabi
      - run: cargo install flip-link
      - run: cargo build --release
      - uses: ./.github/actions/picotool
      - run: cp ./target/thumbv6m-none-eabi/release/lorem lorem.elf
      - run: picotool uf2 convert ./lorem.elf lorem.uf2
      - uses: actions/upload-artifact@v4
        with:
          name: lorem.uf2
          path: ./lorem.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: lorem.elf
          path: ./lorem.elf
