# Build the project and upload binaries as artifacts
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.80.1
        with:
          target: thumbv6m-none-eabi
      - run: cargo build --release
      - run: cargo install elf2uf2-rs --target x86_64-unknown-linux-gnu --version 2.1.1
      - run: elf2uf2-rs ./target/thumbv6m-none-eabi/release/ghostwriter ghostwriter.uf2
      - uses: actions/upload-artifact@v4
        with:
          name: ghostwriter.uf2
          path: ./ghostwriter.uf2

