# Build the project and upload binaries as artifacts
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
        with:
          target: thumbv6m-none-eabi
      - run: cargo install flip-link
      - run: |
          cargo build --release
          # tests for the twine crate
          cargo test --target "$(rustc -vV | grep host | awk '{ print $2; }')" -p twine

      - uses: ./.github/actions/picotool
      - uses: ./.github/actions/upload-firmware
        with:
          bin: lorem
      - uses: ./.github/actions/upload-firmware
        with:
          bin: cyoa
      - uses: ./.github/actions/upload-firmware
        with:
          bin: clicker
