name: Rustfmt
on: push

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
        with:
          target: thumbv6m-none-eabi
          components: rustfmt
      - run: cargo fmt -- --check
